---
- name: Configure host.
  hosts: all

  vars_files:
    - config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks: 
    - import_tasks: tasks/system-init.yml
      when: system_init

    - import_tasks: tasks/flatpak-setup.yml
      when: configure_flatpak

    - import_tasks: tasks/zypper-setup.yml
      when: install_zypper_packages

    - import_tasks: tasks/nvidia-drivers.yml
      when: install_nvidia_drivers

    - import_tasks: tasks/arduino-setup.yml
      when: configure_arduino